using:
  spring:
    schdulefFactory : true

spring:
    datasource:
      jdbc-url : jdbc:mysql://localhost:3306/mms?autoReconnect=true&useUnicode=true&characterEncoding=utf8
      driver-class-name: com.mysql.jdbc.Driver
      username : emoldino
      password : emoldino
# Placeholders batch.*
#    for MySQL:
batch:
  jdbc:
    driver : com.mysql.jdbc.Driver
    url : jdbc:mysql://localhost:3306/mms?autoReconnect=true&useUnicode=true&characterEncoding=utf8
    user : emoldino
    password : emoldino
    testWhileIdle : true
  database:
    incrementer:
      class : org.springframework.jdbc.support.incrementer.MySQLMaxValueIncrementer
  schema:
    script : classpath:/org/springframework/batch/core/schema-mysql.sql

#batch.drop.script=classpath:/org/springframework/batch/core/schema-drop-mysql.sql
#batch.jdbc.testWhileIdle=true
#batch.jdbc.validationQuery=


# Non-platform dependent settings that you might like to change
#batch.data.source.init=true
#batch.table.prefix=BATCH_


